// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNAHIxOrZdHWLv6X35GBB8r9G3ASBo3m8',
    appId: '1:1065569359358:web:cfa20c1ead9e0fa39c5caf',
    messagingSenderId: '1065569359358',
    projectId: 'fruit-hub-93f82',
    authDomain: 'fruit-hub-93f82.firebaseapp.com',
    storageBucket: 'fruit-hub-93f82.firebasestorage.app',
    measurementId: 'G-JC2XYT49X2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWExdxkg6hSxhahfScudVC2RaOWRhvyrA',
    appId: '1:1065569359358:android:70f456586475474c9c5caf',
    messagingSenderId: '1065569359358',
    projectId: 'fruit-hub-93f82',
    storageBucket: 'fruit-hub-93f82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiu_N5tzP5oSCeeLPHlTAowNBByrMR7P0',
    appId: '1:1065569359358:ios:b6bd014809775f999c5caf',
    messagingSenderId: '1065569359358',
    projectId: 'fruit-hub-93f82',
    storageBucket: 'fruit-hub-93f82.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiu_N5tzP5oSCeeLPHlTAowNBByrMR7P0',
    appId: '1:1065569359358:ios:b6bd014809775f999c5caf',
    messagingSenderId: '1065569359358',
    projectId: 'fruit-hub-93f82',
    storageBucket: 'fruit-hub-93f82.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNAHIxOrZdHWLv6X35GBB8r9G3ASBo3m8',
    appId: '1:1065569359358:web:c4cf6f5c71e733ac9c5caf',
    messagingSenderId: '1065569359358',
    projectId: 'fruit-hub-93f82',
    authDomain: 'fruit-hub-93f82.firebaseapp.com',
    storageBucket: 'fruit-hub-93f82.firebasestorage.app',
    measurementId: 'G-GDKH82004Y',
  );
}
